### ISSUE TITLE
Alternative APIs

### ISSUE THREAD

**Issue by jwilm** [BurntSushi/chan-signal#7]
The chan-signal crate is currently tied to the `chan` crate. If I want to deliver signals to, for example, a mio event loop, I need to write a proxy that first receives on the chan receiver and then forwards to the event loop. This is just one case, I can imagine some folks might want to use mpsc channels or some other notification mechanism.

I propose that the `notify` API accept a generic `Notify` (name probably needs bikeshedding) parameter. That might look something like this:

``` rust
/// Thing that can receive signal notifications
pub trait Notify {
    /// Called when a signal arrives
    fn notify(Signal);
}
```

and the `notify` function might look like this:

``` rust
pub fn notify<N: Notify>(notifier: N, signals: &[Signal]) { /* ... */ }
```

A `Notify` based on `chan::Sender` could be added trivially with no overhead compared with the current implementation.

``` rust
pub struct ChanNotify(chan::Sender<Signal>);

impl Notify for ChanNotify {
    #[inline]
    fn notify(signal: Signal) {
        self.0.send(signal);
    }
}
```

An implementation based on `mpsc::Sender`, `mio::Sender`, or whatever else a consumer might want could be added easily in their application.

I realize that this crate is `chan-signal`, so it's kind of tied to the `chan` crate. If these changes make sense, maybe it would be worth refactoring the core signal functionality into a generalized crate like `signal-base` or something with a much better name ;).

**Comment by BurntSushi** [comment]
So... I created this crate because nothing existed at the time and because I didn't want to deal with signal handler functions and their subtle unsafety. I also had super simple use cases. I've always understood the approach this crate took to be sub-optimal because it uses up resources that one may not want it to use. Plus you need to do crazy things like "call this function before spawning any threads." This crate was mostly intended to be something convenient that hooks into the `chan` crate, so I'm not totally convinced that it's worth it to centralize effort on this crate. To be frank, I wouldn't be upset if this crate died and something better replaced it. (I would happily mark it deprecated and forward folks to a new crate if it replaces most sensible use cases.)

**Comment by jwilm** [comment]
That makes sense. The thing that attracted me in the first place was that it was dead simple to add signal handlers and not deal with the variety of unsafety associated with doing so, and I'd like to make that possible with a more flexible API. Would you be ok with the code in this crate being used as a starting point for a new signal handling crate?

**Comment by BurntSushi** [comment]
@jwilm Yes, absolutely. There's barely any code, so no attribution required. :-)

You might also take a look at some of the other issues on this tracker for drawbacks in the current API. I think #2 is particularly damning (related: #4), and of course Windows support #1.

**Comment by jwilm** [comment]
@BurntSushi I would also add to that list the "must be started before spawning other threads" issue. That issue bit me when I first integrated this with onepush. Thanks for highlighting all of the issues btw. Hopefully I can actually make some time to work on such a crate... so much to do and so little time.

**Comment by jwilm** [comment]
Closing this issue since it's essentially `wont fix` for this project.

**Comment by BurntSushi** [comment]
> I would also add to that list the "must be started before spawning other threads" issue.

Right, although, I don't see a way around that given this approach. I think avoiding that will either require traditional async signal handling or perhaps `signalfd` I think, but I'm at the boundary of my knowledge on the topic. :-(
